apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: games-api
  template:
    metadata:
      labels:
        app: games-api
    spec:
      containers:
        - name: games-api
          image: jeremyrbarnes/my-private-images:games-api-1.0
