# Generated by Django 5.2.5 on 2025-08-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
